version: '3.8'

networks:
  controller_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/development/Dockerfile
    networks:
      - controller_network
    container_name: backend_container
    env_file:
      - .env
    ports:
      - "8380:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/development/Dockerfile
    networks:
      - controller_network
    container_name: frontend_container
    env_file:
      - .env
    ports:
      - "3300:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend_container:8080
